config/blog/urls.py
from django.urls import path
from blog.views import (
    ArticleDetail, 
    CategoryList, 
    ArticleList, 
    AuthorList, 
    ArticlePreview,
    BestArticlesView, 
    LikeView, 
    DislikeView,
    SearchList,
    )
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'
urlpatterns = [
    path('', ArticleList.as_view(), name='home'),
    path('page/<int:page>', ArticleList.as_view(), name='home'),
    path('article/<slug>', ArticleDetail.as_view(), name='detail'),
    path('preview/<pk>', ArticlePreview.as_view(), name='preview'),
    path('category/<slug>', CategoryList.as_view(), name='category'),
    path('category/<slug>/page/<int:page>', CategoryList.as_view(), name='category'),
    path('author/<username>', AuthorList.as_view(), name='author'),
    path('author/<username>/page/<int:page>', AuthorList.as_view(), name='author'),
    path('like/<slug>', LikeView, name='like'),
    path('dislike/<slug>', DislikeView, name='dislike'),
    path('best', BestArticlesView.as_view(), name='thebestest'),
    path('search/', SearchList.as_view(), name='search'),
    path('search/page/<int:page>', SearchList.as_view(), name='search'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from account.forms import CustomLogin
from account.views import ChangePassword
from account.views import register
from account.views import send_request, verify


urlpatterns = [
    path('admin/', admin.site.urls),
    # include blog app urls to here
    path('', include('blog.urls')),
    # include login,logout,... urls to here
    path('', include('django.contrib.auth.urls')),
    # include account urls to here
    path('account/', include('account.urls')),
    # custom login,logout,changepassword form
    path("login/", CustomLogin.as_view(), name="login"),
    path("register/", register, name="register"),
    path(
        "password_change/", ChangePassword.as_view(), name="password_change"
    ),
    path('comment/', include('comment.urls')),
    path('request/', send_request, name='request'),
    path('verify/', verify , name='verify'),

]


handler404 = 'blog.views.error_404'

config/blog/models.py
from django.db import models
from django.utils.html import format_html
from account.models import User
from django.urls import reverse
import datetime
from extension.utils import jalali_converter
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment


class ArticleManger(models.Manager):
    def published(self):
        return self.filter(status='p')


class CategoryManger(models.Manager):
    def actived(self):
        return self.filter(status=True)


class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name='آدرس آی پی')


class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True, blank=True,
                               on_delete=models.SET_NULL, related_name='children',
                               verbose_name='دسته اصلی')
    title = models.CharField(max_length=200, verbose_name='عنوان دسنه بندی')
    slug = models.SlugField(max_length=100, unique=True,
                            verbose_name='آدرس دسته بندی')
    status = models.BooleanField(default=True, verbose_name='وضعیت')
    position = models.IntegerField(verbose_name='موقعیت')

    objects = CategoryManger()

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'
        ordering = ['parent__id', 'position']

    def __str__(self):
        return self.title


class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیشنویس'),        #draft
        ('p', 'منتشر شده'),      #published
        ('i', 'درحال بررسی'),    #investigation
        ('b', 'برگشت داده شده'), #back
    )
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL,
                               related_name='articles', verbose_name='نویسنده')
    title = models.CharField(max_length=200, verbose_name='عنوان مقاله')
    slug = models.SlugField(max_length=100, unique=True,
                            verbose_name='آدرس مقاله')
    category = models.ManyToManyField(
        Category, verbose_name='دسته بندی', related_name='articles')
    description = models.TextField(verbose_name='توضیحات')
    thumbnail = models.ImageField(upload_to="image", verbose_name='عکس')
    publish = models.DateTimeField(
        default=datetime.datetime.now, verbose_name='تاریخ انتشار')
    created = models.TimeField(auto_now_add=True, verbose_name='زمان ساخت')
    updated = models.TimeField(auto_now=True, verbose_name='زمان آخرین آپدیت')
    is_special = models.BooleanField(default=False, verbose_name='مقاله ویژه')
    status = models.CharField(
        max_length=1, choices=STATUS_CHOICES, verbose_name='وضعیت')
    comments = GenericRelation(Comment)
    likes = models.ManyToManyField(User, through='ArticleLike', related_name='likes')
    dislikes = models.ManyToManyField(User, through='ArticleDislike', related_name='dislikes')
    views = models.ManyToManyField(IPAddress, through='ArticleHit', blank=True, related_name='views', verbose_name='بازدیدها')

    objects = ArticleManger()

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'
        ordering = ['-publish']

    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()

    def total_dislikes(self):
        return self.dislikes.count()

    # for redirect to home account
    def get_absolute_url(self):
        return reverse('account:articles')

    # to look better date/time publish
    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = 'تاریخ انتشار'

    def publish_category(self):
        return self.category.filter(status=True)

    # show category in panel
    def category_to_str(self):
        return ",".join([category.title for category in self.category.actived()])
    category_to_str.short_description = 'دسته بندی'

    # to show thumbnail article in panel
    def thumbnail_tag(self):
        return format_html("<img height=100 width=120 style='border-radius: 7px;' src='{}'>".format(self.thumbnail.url))
    thumbnail_tag.short_description = 'عکس'


class ArticleHit(models.Model):
	article = models.ForeignKey(Article, on_delete=models.CASCADE)
	ip_address = models.ForeignKey(IPAddress, on_delete=models.CASCADE)
	created = models.DateTimeField(auto_now_add=True)


class ArticleLike(models.Model):
	article = models.ForeignKey(Article, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	created = models.DateTimeField(auto_now_add=True)


class ArticleDislike(models.Model):
	article = models.ForeignKey(Article, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	created = models.DateTimeField(auto_now_add=True)

config/blog/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView, TemplateView
from account.models import User
from .models import Article, Category
from account.mixins import AuthorAccessMixin2
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.db.models import Count, Q


class ArticleList(ListView):
    queryset = Article.objects.published()
    template_name = "blog/home.html"
    context_object_name = "articles"
    paginate_by = 7


def error_404(request, exception):
    return render(request, 'blog/404.html')


class ArticleDetail(DetailView):
    template_name = "blog/post.html"
    context_object_name = "article"

    # get published articles from models
    def get_object(self):
        slug = self.kwargs.get('slug')
        article = get_object_or_404(Article.objects.published(), slug=slug)

        ip_address = self.request.user.ip_address
        if ip_address not in article.views.all():
            article.views.add(ip_address)

        return article

        
    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            # send category with context
            article = get_object_or_404(Article, slug=self.kwargs['slug'])
            total_likes = article.total_likes()
            total_dislikes = article.total_dislikes()
            liked = False
            if article.likes.filter(pk=self.request.user.pk).exists():
                liked = True

            disliked = False
            if article.dislikes.filter(pk=self.request.user.pk).exists():
                disliked = True

            context['total_likes'] = total_likes
            context['total_dislikes'] = total_dislikes
            context['liked'] = liked
            context['disliked'] = disliked

            return context

class ArticlePreview(AuthorAccessMixin2, DetailView):
    template_name = "blog/post.html"
    context_object_name = "article"

    def get_object(self):
        pk = self.kwargs.get('pk')
        obj = get_object_or_404(Article, pk=pk)
        return obj


class CategoryList(ListView):
    template_name = "blog/category.html"
    context_object_name = "articles"

    # get active category
    def get_queryset(self):
        slug = self.kwargs.get('slug')
        global category
        category = get_object_or_404(Category.objects.actived(), slug=slug)
        if slug in ['archive-2022','archive-2021', 'archive-2020']:
            year = 0
            if slug == 'archive-2022':
                year = 2022
            if slug == 'archive-2021':
                year = 2021
            if slug == 'archive-2020':
                year = 2020

            articles = Article.objects.published().filter(Q(publish__year=year))
            return articles

        else:
            # get articles from that category
            articles_category = category.articles.published()

            return articles_category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # send category with context
        context['category'] = category

        return context

    paginate_by = 5

    
class AuthorList(ListView):
    template_name = "blog/author.html"
    context_object_name = "articles"

    def get_queryset(self):
        global author
        username = self.kwargs.get('username')
        author = get_object_or_404(User, username=username)
        # get articles from that user
        articles_author = author.articles.published()

        return articles_author

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author

        return context

    paginate_by = 2


def LikeView(request, slug):
    article = get_object_or_404(Article, slug=slug)
    liked = False
    if article.likes.filter(pk=request.user.pk).exists():
        article.likes.remove(request.user)
        liked = False
    else:
        article.likes.add(request.user)
        article.dislikes.remove(request.user)
        liked = True
    return HttpResponseRedirect(reverse('blog:detail',args=[str(slug)]))


def DislikeView(request, slug):
    article = get_object_or_404(Article, slug=slug)
    disliked = False
    if article.dislikes.filter(pk=request.user.pk).exists():
        article.dislikes.remove(request.user)
        disliked = False
    else:
        article.dislikes.add(request.user)
        article.likes.remove(request.user)
        disliked = True
    return HttpResponseRedirect(reverse('blog:detail',args=[str(slug)]))


class BestArticlesView(TemplateView):
    template_name = "blog/best.html"


class SearchList(ListView):
    template_name = "blog/search.html"
    context_object_name = "articles"

    def get_queryset(self):
        global search
        search = self.request.GET.get('q')
        articles = Article.objects.filter(Q(title__icontains=search) | Q(description__icontains=search))

        return articles

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = search

        return context

    paginate_by = 2

config/comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

config/templates/blog/author.html
{% extends 'blog/base_list.html' %}

{% block header %}
    <h3 class="alert alert-primary text-center">نویسنده  :{{author.get_full_name}}</h3>
{% endblock %}

{% block next_page_url %}
    {% url 'blog:author' author.username page_obj.next_page_number %}
{% endblock %}

{% block previous_page_url %}
    {% url 'blog:author' author.username page_obj.previous_page_number %}
{% endblock %}

config/templates/blog/base.html
{% load static %}
{% load base_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>vigi tech {% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static '/blog/assets/favicon.ico' %}" />

    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>

    <link href="{% static 'blog/css/kossher.css' %}" rel="stylesheet" />
    <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet" />
</head>

{% if user.blocked %}
    <div style="padding: 200px; padding-top: 200px; padding-right: 480px;">
        <head>
            <title>
            Window alert() Method in HTML
            </title>
            <style>
                h1 {
                    color: green;
                }
                
                h2 {
                    font-family: Impact;
                }
                
                body {
                    text-align: center;
                }
            </style>
        </head>
        
        <body>
        
            <h1>ریدی داداش😂</h1>
            <h2>
                بلاک شدی  
            </h2>
        
            <p>
                برای اینکه بفهمی چجوری آنبلاک شی روی دکمه پایینی کلیک کن 
            </p>
        
            <button ondblclick="myalert()">
            دیدن پیام
            </button>
        
            <script>
                function myalert() {
                    alert("برای آنبلاک شدن\n " +
                        "به مدیر یه " + 
                                "پیام بده");
                }
            </script>
        
        </body>
    </div>
{% else %}
    <body>

        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'blog:home' %}">{% title %}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                {% category_navbar %}
            </div>
        </nav>


        {% block main %}

        {% endblock %}

        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static '/blog/js/scripts.js' %}"></script>
    </body>

    </html>
{% endif %}

config/templates/blog/base_list.html
{% extends 'blog/base.html' %}
{% load static %}
{% load base_tags %}
{% load humanize %}


{% block main %}
<header class="masthead" style="background-image: url('{% static '/blog/assets/img/home-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>ویجی تک</h1>
                </div>
            </div>
        </div>
    </div>
</header>


<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            {% block header %}{% endblock %}
            <aside style="width: 300px;
                          left: 25px;
                          position: absolute;"
                          >
                {% top_articles_month %}
                {% top_articles_by_like_month %}
                {% hot_articles_month %}
            </aside>
            {% for article in articles %}
                <div class="post-preview">
                    <a href="{% url 'blog:detail' article.slug %}">
                        <h2 class="post-title" style="font-size: 30px;">
                            {{article.title}}
                            {% if article.is_special %}
                                <span class="badge badge-danger" style="font-size: 12px; background-color: red;">ویژه</span>
                            {% endif %}
                        </h2>
                        <h3 class="post-subtitle" style="font-size: 18px;">
                            {{ article.description|striptags|truncatewords:30 }}
                        </h3>
                    </a>
                    <p class="post-meta">
                        <a href="{% url 'blog:author' article.author.username %}" style="font-size: 12px;">نوشته شده توسط : {{article.author.get_full_name}}</a>
                        <h6 style="font-size: 12px;">تاریخ انتشار : {{article.jpublish}}</h6>
                        {% for category in article.category.actived %}
                            <h6 style="font-size: 12px;"><a href="{% url 'blog:category' category.slug %}">#{{category.title}}</a>
                            </h6>
                        {% endfor %}
                        <span style="font-size: 14px;">بازدید ها : {{article.views.count}}</span>
                    </p>
                    <hr>
                </div>
            {% empty %}
                <p>متاسفانه موردی برای نمایش وجود ندارد</p>
            {% endfor %}
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Pager-->
            <div class="clearfix pager-botton">
                {% if is_paginated %}
                <div class="clearfix pager-botton">
                    {% if page_obj.has_next %}
                    <div class="d-flex justify-content-end float-right mb-4"><a class="btn btn-primary text-uppercase"
                            href="{% block next_page_url %}{% endblock %}">پست های قبلی &larr;</a></div>
                    {% endif %}

                    {% if page_obj.has_previous %}
                    <div class="d-flex justify-content-end float-right mb-4"><a class="btn btn-primary text-uppercase"
                            href="{% block previous_page_url %}{% endblock%}">&rarr; پست های جدید</a></div>
                    {% endif %}
                </div>
            {% endif %}
            </div>        
        </div>
    </div>
</div>
{% endblock %}

config/templates/blog/best.html
{% extends 'blog/base.html' %}
{% load static %}
{% load base_tags %}


{% block main %}
    <header class="masthead" style="background-image: url('{% static '/blog/assets/img/home-bg.jpg' %}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>ویجی تک</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>


    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                {% hot_articles_month %}
                {% hot_articles_anytime %}
                {% top_articles_month %}
                {% top_articles_anytime %}
                {% top_articles_year %}
                {% top_articles_by_like_month %}
                {% top_articles_by_like_year %}
                {% top_articles_by_like_anytime %}
                {% top_articles_by_dislike_month %}
                {% top_articles_by_dislike_anytime %}
            </div>
        </div>
    </div>
{% endblock %}

config/templates/blog/category.html
{% extends 'blog/base_list.html' %}

{% block header %}
    <h3 class="alert alert-primary text-center">دسته بندی :{{category.title}}</h3>
{% endblock %}

{% block next_page_url %}
    {% url 'blog:category' category.slug page_obj.next_page_number %}
{% endblock %}

{% block previous_page_url %}
    {% url 'blog:category' category.slug page_obj.previous_page_number %}
{% endblock %}

config/templates/blog/home.html
{% extends 'blog/base_list.html' %}

{% block header %}{% endblock %}

{% block next_page_url %}
    {% url 'blog:home' page_obj.next_page_number %}
{% endblock %}

{% block previous_page_url %}
    {% url 'blog:home' page_obj.previous_page_number %}
{% endblock %}

config/templates/blog/post.html
{% extends 'blog/base.html' %}
{% load static %}
{% load comment_tags %}
{% load base_tags %}


{% block title %}
   | {{article.title}}
{% endblock %}

{% block main %}
        <header class="masthead" style="width: 1340px; height: 700px; background-image: url('{{ article.thumbnail.url }}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1 style="font-size: 40px;">
                                {{article.title}}
                            </h1>
                                {% if article.is_special %}
                                    <span class="badge badge-danger" style="font-size: 14px; background-color: red;">ویژه</span>
                                {% endif %}
                            <time>{{article.jpublish}}</time>
                            <div>
                                <p>بازدید ها : {{article.views.count}}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <aside style="width: 300px;
                    right: 25px;
                    position: absolute;"
                    >
                        {% top_articles_month %}
                        {% top_articles_by_like_month %}
                        {% hot_articles_month %}
                    </aside>
                    <div class="col-md-10 col-lg-8 col-xl-7 text-jusify" style="width: 800px;">
                        <article style="width: 800px;">
                            {% if article.is_special %}
                                {% if user.is_authenticated and user.is_special_user or user.is_superuser or user == article.author %}
                                    {{ article.description|safe }}
                                {% else %}
                                    {{ article.description|striptags|truncatewords:30 }}
                                    <p class="alert alert-secondary" style="background-color: #7b0404 !important;">این مقاله ویژه است و برای دیدنش باید <a class="alert-link" href="#">اشتراک ویژه</a> تهیه کنید</p>    
                                {% endif %}
                            {% else %}
                                {{ article.description|safe }}
                            {% endif %}
                        </article>
                        <div>
                            {% if user.is_authenticated %}
                                {% if liked %}
                                        <span class="js-like-number text-dark"><a href="{% url 'blog:like' article.slug %}">{{total_likes}}
                                            <i class="fa-solid fa-thumbs-up"></i>
                                        </a></span>
                                {% elif liked == False %}
                                        <span class="js-like-number text-dark"><a href="{% url 'blog:like' article.slug %}">{{total_likes}}
                                            <i class="fa-regular fa-thumbs-up"></i>
                                        </a></span>
                                {% endif %}
                                {% if disliked %}
                                    <span class="js-like-number text-dark"><a href="{% url 'blog:dislike' article.slug %}">{{total_dislikes}}
                                        <i class="fa-solid fa-thumbs-down"></i>
                                    </a></span>
                                {% elif disliked == False %}
                                    <span class="js-like-number text-dark"><a href="{% url 'blog:dislike' article.slug %}">{{total_dislikes}}
                                        <i class="fa-regular fa-thumbs-down"></i>
                                    </a></span>
                                {% endif %}
                            {% else %}
                                <span style="padding: 12px;" class="badge badge-danger">برای لایک کردن باید <a href="{% url 'login' %}">وارد</a> شوید</span>
                                <span class="js-like-number text-dark"><a href="">{{total_likes}}
                                    <i class="fa-regular fa-thumbs-up"></i>
                                <span class="js-like-number text-dark"><a href="">{{total_dislikes}}
                                    <i class="fa-regular fa-thumbs-down"></i>
                            {% endif %}
                        </div>
                        <hr>
                        <div>
                            {% render_comments article request %}
                            {% include_bootstrap %}
                        </div>
                    </div>
                </div>
            </div>
        </article>
{% endblock %}

config/templates/blog/search.html
{% extends 'blog/base_list.html' %}

{% block header %}
    <h3 class="alert alert-primary text-center">جستجو  :{{search}}</h3>
{% endblock %}

{% block next_page_url %}
    {% url 'blog:search' page_obj.next_page_number %}?q={{search}}
{% endblock %}

{% block previous_page_url %}
    {% url 'blog:search' page_obj.previous_page_number %}?q={{search}}
{% endblock %}